/*
    This file has been generated by bvtidl.pl. DO NOT MODIFY!
*/
#ifndef __BVTLOGGER_H__
#define __BVTLOGGER_H__

#include <bvt_c/bvt_retval.h>

#ifndef DOXY_IGNORE
#ifdef _WIN32
#	ifdef BUILDING_BVTSDK
#		define BVTSDK_EXPORT __declspec(dllexport)
#	else
#		define BVTSDK_EXPORT __declspec(dllimport)
#	endif
#	if !defined(BVTSDK_NO_DEPRECATE) && _MSC_VER >= 1310
#		define BVTSDK_EXPORT_OBSOLETE BVTSDK_EXPORT __declspec(deprecated("This will be removed in a future version of the BlueView SDK"))
#	else
#		define BVTSDK_EXPORT_OBSOLETE BVTSDK_EXPORT
#	endif
#else
#	if __GNUC__ >= 4
#		define BVTSDK_EXPORT __attribute__ ((visibility ("default")))
#	else
#		define BVTSDK_EXPORT
#	endif
#	if !defined(BVTSDK_NO_DEPRECATE) && ((__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1)))
#		define BVTSDK_EXPORT_OBSOLETE BVT_EXPORT __attribute__((__deprecated__("This will be removed in a future version of the BlueView SDK")))
#	else
#		define BVTSDK_EXPORT_OBSOLETE BVTSDK_EXPORT
#	endif
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/** @file
 * @defgroup BVTLogger BVTLogger
 * @brief
 * The SDK is capable of producing a significant amount of debugging 
 * output.  The Logger object exists to allow the user to control 
 * (or disable) the output.  Users can also use Logger to add their
 * own custom log messages.
 * @{
*/

enum BVTLogLevel
{
	BVT_LOGLEVEL_NONE = -1,
	BVT_LOGLEVEL_CRITICAL = 0,
	BVT_LOGLEVEL_WARNING = 1,
	BVT_LOGLEVEL_STATUS = 2
};

/** Set the log threshold level.  Events above level
 * will be logged to the target.
 * @param level Log level 
 */
BVTSDK_EXPORT void BVTLogger_SetLevel(int level);

/** The log target can be a filename, "stdout", "stderr", or "null".
 * If null is specified, log output is disabled.
 * @param target File/device to log output to 
 */
BVTSDK_EXPORT RetVal BVTLogger_SetTarget(const char* target);

/** BVTLogger_Write a message to the log.
 * @param level The log level of the message 
 * @param message A string to log 
 */
BVTSDK_EXPORT void BVTLogger_Write(int level, const char* message);

/** BVTLogger_Write a message to the log. This function is similar to printf in 
 * that the format parameter controls how the argument list is interpreted. 
 * See the printf documentation for more information.
 * @param level The log level of the message 
 * @param format A printf-style string to log 
 */
BVTSDK_EXPORT void BVTLogger_WriteFormatted(int level, const char* format, ... );

/** @}*/

#ifdef __cplusplus
}
#endif

#endif
