/*
    This file has been generated by bvtidl.pl. DO NOT MODIFY!
*/
#ifndef __BVTSDK_H__
#define __BVTSDK_H__

#include <bvt_c/bvt_retval.h>

#ifndef DOXY_IGNORE
#ifdef _WIN32
#	ifdef BUILDING_BVTSDK
#		define BVTSDK_EXPORT __declspec(dllexport)
#	else
#		define BVTSDK_EXPORT __declspec(dllimport)
#	endif
#	if !defined(BVTSDK_NO_DEPRECATE) && _MSC_VER >= 1310
#		define BVTSDK_EXPORT_OBSOLETE BVTSDK_EXPORT __declspec(deprecated("This will be removed in a future version of the BlueView SDK"))
#	else
#		define BVTSDK_EXPORT_OBSOLETE BVTSDK_EXPORT
#	endif
#else
#	if __GNUC__ >= 4
#		define BVTSDK_EXPORT __attribute__ ((visibility ("default")))
#	else
#		define BVTSDK_EXPORT
#	endif
#	if !defined(BVTSDK_NO_DEPRECATE) && ((__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 1)))
#		define BVTSDK_EXPORT_OBSOLETE BVT_EXPORT __attribute__((__deprecated__("This will be removed in a future version of the BlueView SDK")))
#	else
#		define BVTSDK_EXPORT_OBSOLETE BVTSDK_EXPORT
#	endif
#endif
#endif

#ifdef __cplusplus
extern "C" {
#endif

/** @file
 * @defgroup BVTSDK BVTSDK
 * @brief
 * Global initialization and cleanup functions.
 * @{
*/

/** Perform initialization of the SDK.
 */
BVTSDK_EXPORT void BVTSDK_Init();

/** Cleans up various SDK structures.
 */
BVTSDK_EXPORT void BVTSDK_Shutdown();

/** Return the major version number of the SDK.
 */
BVTSDK_EXPORT int BVTSDK_MajorVersion();

/** Return the minor version of the SDK.
 */
BVTSDK_EXPORT int BVTSDK_MinorVersion();

/** Return the build number of the SDK.
 */
BVTSDK_EXPORT int BVTSDK_BuildNumber();

/** @}*/

#ifdef __cplusplus
}
#endif

#endif
