#!/bin/sh
### BEGIN INIT INFO
# Provides:          nims
# Required-Start:    $network $local_fs $remote_fs
# Required-Stop:     $network $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: NIMS processes
# Description:       Manage the Nekton Interactive Monitoring System server
### END INIT INFO
# System Startup for NIMS
# to be installed in /etc/init.d

APPLICATION_PATH=/home/nims/bin

# make sure our application is there
test -x $APPLICATION_PATH/nims || exit 0

. /lib/lsb/init-functions

case $1 in

   start)
       # if init_is_upstart; then
       #   exit 1
       # fi
      log_daemon_msg "Starting NIMS applications" nims
      if ! start-stop-daemon --start --chuid nims  --chdir $APPLICATION_PATH \
         --exec $APPLICATION_PATH/nims -- -D; then
            log_end_msg 1
            exit 1
      fi
      log_end_msg 0
      ;; 

   stop)
      # if init_is_upstart; then
      #   exit 0
      # fi
      log_daemon_msg "Stopping NIMS applications" nims
      start-stop-daemon --stop --signal INT --exec $APPLICATION_PATH/nims
      log_end_msg 0
      ;;
      
   restart)
      # if init_is_upstart; then
      #   exit 1
      # fi
    	$0 stop
    	sleep 1
    	$0 start
    	;;
   *)
      echo "Usage: nims.sh  {start|stop|restart}"
      exit 1
      ;;
esac

exit 0

