"""
This file was generated by bvtidl.pl.
Your changes will most likely be lost.
"""

from ctypes import *
import sys
import sdkerror


class ColorImage(object):
    """
    Store a color image.  The API is nearly identical to MagImage.  The main difference is the 
    pixel datatype. In ColorImage, each pixel is a single unsigned int. 
    - Byte 0: Red Value
    - Byte 1: Green Value
    - Byte 2: Blue Value
    - Byte 3: Alpha Value
    """
    def __init__(self, handle=None):
        super(ColorImage, self).__setattr__("_initialized", False)
        self._deleted = False
        if handle is None:
            self._handle = dll.BVTColorImage_Create()
        else:
            self._handle = handle
        super(ColorImage, self).__setattr__("_initialized", True)

    def __del__(self):
        self._deleted = True
        dll.BVTColorImage_Destroy(self._handle)

    def __setattr__(self, name, value):
        """ Don't allow setting non-existent attributes on this class
        """
        if self._initialized and not hasattr(self, name):
            raise AttributeError("%s instance has no attribute '%s'" % (self.__class__.__name__, name))
        super(ColorImage, self).__setattr__(name, value)

    def get_pixel(self, row, col):
        """
        Return the value of the pixel at (row, col)
        """
        pixel = c_uint()
        error_code = dll.BVTColorImage_GetPixel(self._handle, row, col, byref(pixel))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return pixel.value

    def set_pixel(self, row, col, pixel):
        """
        Set the value of the pixel at (row, col)
        """
        error_code = dll.BVTColorImage_SetPixel(self._handle, row, col, pixel)
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)

    def try_set_pixel(self, row, col, pixel, default_value):
        """
        Set the value of the pixel at (row, col)
        """
        error_code = dll.BVTColorImage_SetPixel(self._handle, row, col, pixel)
        if (0 != error_code):
            return default_value

    def get_row(self, row):
        """
        Return a pointer to a row of pixels 
        """
        rowPointer = c_uint()
        error_code = dll.BVTColorImage_GetRow(self._handle, row, byref(rowPointer))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return rowPointer.value

    @property
    def bits(self):
        """
        Return a pointer to the entire image.
        The image or organized in Row-Major order (just like C/C++).
        """
        bitsPointer = c_uint()
        error_code = dll.BVTColorImage_GetBits(self._handle, byref(bitsPointer))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return bitsPointer.value

    def copy_bits(self, data, len):
        """
        Copy the raw image data to the user specified buffer. See GetBits for more info.
        """
        error_code = dll.BVTColorImage_CopyBits(self._handle, data, len)
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)

    @property
    def boundary_count(self):
        """
        Return the number of boundaries for this image. A boundary defines
        the limit of data for a transducer, and is always a line.
        """
        count = c_int()
        error_code = dll.BVTColorImage_GetBoundaryCount(self._handle, byref(count))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return count.value

    def get_boundary_line_segment(self, index, x0, y0, x1, y1):
        """
        Get the true line segment for the boundary at the specified index.
        """
        error_code = dll.BVTColorImage_GetBoundaryLineSegment(self._handle, index, byref(x0), byref(y0), byref(x1), byref(y1))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)

    def get_boundary_radians_approximate(self, index):
        """
        Get the approximate bearing angle for the boundary at the specified index. A boundary may not necessarily start at the origin, so this
        approximation may be too imprecise for some applications.
        """
        radians = c_float()
        error_code = dll.BVTColorImage_GetBoundaryRadiansApproximate(self._handle, index, byref(radians))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return radians.value

    def save_ppm(self, file_name):
        """
        Save the image in PPM (PortablePixMap) format. http://en.wikipedia.org/wiki/Netpbm_format
        """
        error_code = dll.BVTColorImage_SavePPM(self._handle, (file_name))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)

    @property
    def height(self):
        """
        Return the height (in pixels) of this image
        """
        height = c_int()
        error_code = dll.BVTColorImage_GetHeight(self._handle, byref(height))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return height.value

    @property
    def width(self):
        """
        Return the width (in pixels) of this image
        """
        width = c_int()
        error_code = dll.BVTColorImage_GetWidth(self._handle, byref(width))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return width.value

    @property
    def max_range_of_pixel(self):
        """
        Return the max range (in meters) to a non-blank pixel in the image
        """
        maxRange = c_float()
        error_code = dll.BVTColorImage_GetMaxRangeOfPixel(self._handle, byref(maxRange))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return maxRange.value

    @property
    def image_type(self):
        """
        
        """
        type = c_int()
        error_code = dll.BVTColorImage_GetImageType(self._handle, byref(type))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return type.value

    @property
    def range_resolution(self):
        """
        Return the range resolution of this image.
        The resolution is returned in meters per pixel row.
        """
        resolution = c_double()
        error_code = dll.BVTColorImage_GetRangeResolution(self._handle, byref(resolution))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return resolution.value

    @property
    def bearing_resolution(self):
        """
        Only valid for R-Theta images.
        Returns the bearing resolution, in degrees per pixel column.
        """
        resolution = c_double()
        error_code = dll.BVTColorImage_GetBearingResolution(self._handle, byref(resolution))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return resolution.value

    @property
    def origin_row(self):
        """
        Retrieve the image row of the origin.
        In most cases the origin row will be outside of the image boundaries (i.e., negative). The origin is the 'location' (in pixels) of the sonar head in image plane.
        """
        row = c_int()
        error_code = dll.BVTColorImage_GetOriginRow(self._handle, byref(row))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return row.value

    @property
    def origin_col(self):
        """
        Retrieve the image column of the origin.
        The origin is the 'location' (in pixels) of the
        sonar head in image plane.
        """
        column = c_int()
        error_code = dll.BVTColorImage_GetOriginCol(self._handle, byref(column))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return column.value

    def get_pixel_range(self, row, col):
        """
        Retrieve the range (from the sonar head) of the specified pixel (in meters)
        """
        range = c_double()
        error_code = dll.BVTColorImage_GetPixelRange(self._handle, row, col, byref(range))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return range.value

    def get_pixel_relative_bearing(self, row, col):
        """
        Retrieve the bearing relative to the sonar head of the specified pixel
        """
        bearing = c_double()
        error_code = dll.BVTColorImage_GetPixelRelativeBearing(self._handle, row, col, byref(bearing))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return bearing.value

    def get_pixel_coordinate_at_range_bearing(self, range, bearing, x, y):
        """
        Return the pixel coordinate at the specified physical location.
        The returned coordinate may be outside this image's bounds.
        """
        error_code = dll.BVTColorImage_GetPixelCoordinateAtRangeBearing(self._handle, range, bearing, byref(x), byref(y))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)

    def get_pixel_coordinate_at_xy(self, x_meters, y_meters, x, y):
        """
        Return the pixel coordinate at the specified physical location in the sonar's frame.
        The returned coordinate may be outside this image's bounds.
        """
        error_code = dll.BVTColorImage_GetPixelCoordinateAtXY(self._handle, x_meters, y_meters, byref(x), byref(y))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)

    @property
    def fov_min_angle(self):
        """
        Return the minimum angle for the sonar's imaging field of view. 
        The angle is returned in degrees and referenced with respect to sonar head boresight (clockwise-positive).
        """
        angle = c_float()
        error_code = dll.BVTColorImage_GetFOVMinAngle(self._handle, byref(angle))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return angle.value

    @property
    def fov_max_angle(self):
        """
        Return the maximum angle for the sonar's imaging field of view. 
        The angle is returned in degrees and referenced with respect to sonar head boresight (clockwise-positive).
        """
        angle = c_float()
        error_code = dll.BVTColorImage_GetFOVMaxAngle(self._handle, byref(angle))
        if (0 != error_code):
            raise sdkerror.SDKError(error_code)
        return angle.value


    def get_handle(self):
        """
        SDK object pointer
        """
        return self._handle
if "win32" in sys.platform:
    dll_name = "bvtsdk4.dll"
elif "darwin" in sys.platform:
    dll_name = "libbvtsdk.dylib"
else:
    dll_name = "libbvtsdk.so"
dll = CDLL(dll_name)
dll.BVTColorImage_Create.restype = c_void_p
dll.BVTColorImage_Destroy.restype = None
dll.BVTColorImage_Destroy.argtypes = (c_void_p,)
dll.BVTColorImage_GetPixel.restype = c_int
dll.BVTColorImage_GetPixel.argtypes = (c_void_p, c_int, c_int, POINTER(c_uint), )
dll.BVTColorImage_SetPixel.restype = c_int
dll.BVTColorImage_SetPixel.argtypes = (c_void_p, c_int, c_int, c_int, )
dll.BVTColorImage_GetRow.restype = c_int
dll.BVTColorImage_GetRow.argtypes = (c_void_p, c_int, POINTER(c_uint), )
dll.BVTColorImage_GetBits.restype = c_int
dll.BVTColorImage_GetBits.argtypes = (c_void_p, POINTER(c_uint), )
dll.BVTColorImage_CopyBits.restype = c_int
dll.BVTColorImage_CopyBits.argtypes = (c_void_p, POINTER(c_int), c_int, )
dll.BVTColorImage_GetBoundaryCount.restype = c_int
dll.BVTColorImage_GetBoundaryCount.argtypes = (c_void_p, POINTER(c_int), )
dll.BVTColorImage_GetBoundaryLineSegment.restype = c_int
dll.BVTColorImage_GetBoundaryLineSegment.argtypes = (c_void_p, c_int, POINTER(c_float), POINTER(c_float), POINTER(c_float), POINTER(c_float), )
dll.BVTColorImage_GetBoundaryRadiansApproximate.restype = c_int
dll.BVTColorImage_GetBoundaryRadiansApproximate.argtypes = (c_void_p, c_int, POINTER(c_float), )
dll.BVTColorImage_SavePPM.restype = c_int
dll.BVTColorImage_SavePPM.argtypes = (c_void_p, c_char_p, )
dll.BVTColorImage_GetHeight.restype = c_int
dll.BVTColorImage_GetHeight.argtypes = (c_void_p, POINTER(c_int), )
dll.BVTColorImage_GetWidth.restype = c_int
dll.BVTColorImage_GetWidth.argtypes = (c_void_p, POINTER(c_int), )
dll.BVTColorImage_GetMaxRangeOfPixel.restype = c_int
dll.BVTColorImage_GetMaxRangeOfPixel.argtypes = (c_void_p, POINTER(c_float), )
dll.BVTColorImage_GetImageType.restype = c_int
dll.BVTColorImage_GetImageType.argtypes = (c_void_p, POINTER(c_int), )
dll.BVTColorImage_GetRangeResolution.restype = c_int
dll.BVTColorImage_GetRangeResolution.argtypes = (c_void_p, POINTER(c_double), )
dll.BVTColorImage_GetBearingResolution.restype = c_int
dll.BVTColorImage_GetBearingResolution.argtypes = (c_void_p, POINTER(c_double), )
dll.BVTColorImage_GetOriginRow.restype = c_int
dll.BVTColorImage_GetOriginRow.argtypes = (c_void_p, POINTER(c_int), )
dll.BVTColorImage_GetOriginCol.restype = c_int
dll.BVTColorImage_GetOriginCol.argtypes = (c_void_p, POINTER(c_int), )
dll.BVTColorImage_GetPixelRange.restype = c_int
dll.BVTColorImage_GetPixelRange.argtypes = (c_void_p, c_int, c_int, POINTER(c_double), )
dll.BVTColorImage_GetPixelRelativeBearing.restype = c_int
dll.BVTColorImage_GetPixelRelativeBearing.argtypes = (c_void_p, c_int, c_int, POINTER(c_double), )
dll.BVTColorImage_GetPixelCoordinateAtRangeBearing.restype = c_int
dll.BVTColorImage_GetPixelCoordinateAtRangeBearing.argtypes = (c_void_p, c_float, c_float, POINTER(c_int), POINTER(c_int), )
dll.BVTColorImage_GetPixelCoordinateAtXY.restype = c_int
dll.BVTColorImage_GetPixelCoordinateAtXY.argtypes = (c_void_p, c_float, c_float, POINTER(c_int), POINTER(c_int), )
dll.BVTColorImage_GetFOVMinAngle.restype = c_int
dll.BVTColorImage_GetFOVMinAngle.argtypes = (c_void_p, POINTER(c_float), )
dll.BVTColorImage_GetFOVMaxAngle.restype = c_int
dll.BVTColorImage_GetFOVMaxAngle.argtypes = (c_void_p, POINTER(c_float), )

