"""
This file was generated by bvtidl.pl.
Your changes will most likely be lost.
"""

from ctypes import *
import sys
import sdkerror


class Error(object):
    """
    The Error object provides access to the SDK's error reporting 
    system.  This allows the user to map from an error number to 
    a human readable description of the error.
    """
    def __setattr__(self, name, value):
        """ Don't allow setting non-existent attributes on this class
        """
        if self._initialized and not hasattr(self, name):
            raise AttributeError("%s instance has no attribute '%s'" % (self.__class__.__name__, name))
        super(Error, self).__setattr__(name, value)

    @staticmethod
    def get_string(code):
        """
        Return a description of the error
        """
        return (dll.BVTError_GetString(code))

    @staticmethod
    def get_name(code):
        """
        Return a the error number as a string.
        """
        return (dll.BVTError_GetName(code))


if "win32" in sys.platform:
    dll_name = "bvtsdk4.dll"
elif "darwin" in sys.platform:
    dll_name = "libbvtsdk.dylib"
else:
    dll_name = "libbvtsdk.so"
dll = CDLL(dll_name)
dll.BVTError_GetString.restype = c_char_p
dll.BVTError_GetString.argtypes = (c_int, )
dll.BVTError_GetName.restype = c_char_p
dll.BVTError_GetName.argtypes = (c_int, )

