"""
This file was generated by bvtidl.pl.
Your changes will most likely be lost.
"""

from ctypes import *
import sys
import sdkerror


class SDK(object):
    """
    Global initialization and cleanup functions.
    """
    def __setattr__(self, name, value):
        """ Don't allow setting non-existent attributes on this class
        """
        if self._initialized and not hasattr(self, name):
            raise AttributeError("%s instance has no attribute '%s'" % (self.__class__.__name__, name))
        super(SDK, self).__setattr__(name, value)

    @staticmethod
    def init():
        """
        Perform initialization of the SDK.
        """
        dll.BVTSDK_Init()

    @staticmethod
    def shutdown():
        """
        Cleans up various SDK structures.
        """
        dll.BVTSDK_Shutdown()

    @staticmethod
    def major_version():
        """
        Return the major version number of the SDK.
        """
        return dll.BVTSDK_MajorVersion()

    @staticmethod
    def minor_version():
        """
        Return the minor version of the SDK.
        """
        return dll.BVTSDK_MinorVersion()

    @staticmethod
    def build_number():
        """
        Return the build number of the SDK.
        """
        return dll.BVTSDK_BuildNumber()


if "win32" in sys.platform:
    dll_name = "bvtsdk4.dll"
elif "darwin" in sys.platform:
    dll_name = "libbvtsdk.dylib"
else:
    dll_name = "libbvtsdk.so"
dll = CDLL(dll_name)
dll.BVTSDK_Init.restype = None
dll.BVTSDK_Init.argtypes = ()
dll.BVTSDK_Shutdown.restype = None
dll.BVTSDK_Shutdown.argtypes = ()
dll.BVTSDK_MajorVersion.restype = c_int
dll.BVTSDK_MajorVersion.argtypes = ()
dll.BVTSDK_MinorVersion.restype = c_int
dll.BVTSDK_MinorVersion.argtypes = ()
dll.BVTSDK_BuildNumber.restype = c_int
dll.BVTSDK_BuildNumber.argtypes = ()

